name: Android Default Branch CI

on:
  push:
    branches:
      - shunf4_mod
      - riv_mod
      - master
      - 'fix/*'
      - 'feat/*'

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build APK
        run: bash ./gradlew assembleRelease --stacktrace

      - name: Sign Full Version APK
        uses: r0adkll/sign-android-release@v1
        id: sign_full
        with:
          releaseDirectory: app/build/outputs/apk/full/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          
      - name: Sign Iffiltered Version APK
        uses: r0adkll/sign-android-release@v1
        id: sign_iffiltered
        with:
          releaseDirectory: app/build/outputs/apk/iffiltered/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Full Version APK
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-full-release
          path: ${{ steps.sign_full.outputs.signedReleaseFile }}

      - name: Upload Iffiltered Version APK
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-iffiltered-release
          path: ${{ steps.sign_iffiltered.outputs.signedReleaseFile }}
